### ISSUE TITLE
Pod missing from Cocoapods

### ISSUE THREAD

**Issue by kauffmanelia** [yahoo/YMTreeMap#1]
The podspec for YMTreeMap is missing from the Cocoapods repo and from the cocoapods.org pod reference; thus, simple install via Cocoapods doesn't work.

**Comment by adamkaplan** [comment]
Huh, thanks for the note. I'm not sure how that happened, but I will publish now.

**Comment by adamkaplan** [comment]
Published: https://cocoapods.org/pods/YMTreeMap

Thanks @kauffmanelia.
